train:
    max_iter: 20
    save_every_iterations: 50
    optimizer_class: Adam
    optimizer_param:
        lr: 5.e-5
    resume: False

logger:
    dir_name: /sdf/home/j/junjie/sdf-data/FM/playground/first_trial/logs
    file_name: "log_first_trial.csv"
    log_every_nsteps: 1
    analysis:
        vis_bias:
            threshold: 5e-5

model:
    network:
        in_features: 3
        hidden_features: 256
        hidden_layers: 5
        out_features: 64
    ckpt_file: ""
    output_scale:
        fix: True
transform_vis:
    vmax: 1.0
    eps: 1.e-7
    sin_out: True
data:
    dataset:
        weight:
            method: "vis"
            threshold: 1.e-8
            factor: 1.e+6
    loader:
        batch_size: 100000
        num_workers: 4
        shuffle: True
        pin_memory: True
        drop_last: True